// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlOb8qEkHPcY9rWrxBEU1Ll8DwSf2uT_s',
    appId: '1:921452174910:web:093c81d62946c7074bbb6f',
    messagingSenderId: '921452174910',
    projectId: 'login-fbeda',
    authDomain: 'login-fbeda.firebaseapp.com',
    storageBucket: 'login-fbeda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd273wSpAgz4utCgmpGuUNkiLyJ6zBWJk',
    appId: '1:921452174910:android:292d3310440d98d84bbb6f',
    messagingSenderId: '921452174910',
    projectId: 'login-fbeda',
    storageBucket: 'login-fbeda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6UlR5M7sNbos7XzAEtX2xiB2VkzCw3wI',
    appId: '1:921452174910:ios:59dbc486c9b3be354bbb6f',
    messagingSenderId: '921452174910',
    projectId: 'login-fbeda',
    storageBucket: 'login-fbeda.appspot.com',
    iosClientId: '921452174910-236gdjsv7mei744lmikimuh9o8beehgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6UlR5M7sNbos7XzAEtX2xiB2VkzCw3wI',
    appId: '1:921452174910:ios:59dbc486c9b3be354bbb6f',
    messagingSenderId: '921452174910',
    projectId: 'login-fbeda',
    storageBucket: 'login-fbeda.appspot.com',
    iosClientId: '921452174910-236gdjsv7mei744lmikimuh9o8beehgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
